/**
 * Destructive filter registry.
 *
 * Unlike adjustment layers (which are non-destructive fullscreen passes over
 * the live composite), filters render a SINGLE raster layer's pixels through
 * one or more shader passes into an RGBA8 target, read the result back, and
 * replace the layer's CPU source as one undo step. Some filters need two passes
 * (separable blur) — the engine drives the pass loop, ping-ponging between two
 * RGBA8 targets, and a filter declares how many passes it wants and supplies
 * per-pass uniforms.
 *
 * All filter shaders operate on STRAIGHT-alpha sRGB layer textures (the same
 * encoding a layer's source uses), so they are display-referred. Each shader
 * samples `u_src` (the previous pass / the layer) and writes the next pass.
 *
 * The registry is data-driven (`paramsSchema`) so dialogs are generated by the
 * UI without hard-coding per-filter forms.
 */
import type { ParamField, AdjustmentParams as ParamBag } from "./adjustments";

export type FilterType =
  | "gaussian_blur"
  | "motion_blur"
  | "sharpen"
  | "unsharp_mask"
  | "add_noise"
  | "pixelate"
  | "find_edges"
  | "emboss";

export type FilterParams = ParamBag;

/** Per-pass uniform setter context. */
export interface FilterPassContext {
  gl: WebGL2RenderingContext;
  loc: (name: string) => WebGLUniformLocation | null;
  params: FilterParams;
  /** 0-based pass index (for multi-pass filters like separable blur). */
  pass: number;
  /** Layer pixel dimensions (for texel-size uniforms). */
  width: number;
  height: number;
}

export interface FilterDef {
  type: FilterType;
  label: string;
  defaults: FilterParams;
  paramsSchema: ParamField[];
  /** Fragment shader source (uses QUAD_VERT; samples u_src). */
  fragSource: string;
  /**
   * Number of render passes. May depend on params (e.g. a 0-radius blur could
   * short-circuit, but we keep it simple and always run the declared count).
   */
  passes: (params: FilterParams) => number;
  /** Push per-pass uniforms (the engine binds u_src + sets u_texel for you). */
  setUniforms: (ctx: FilterPassContext) => void;
}

// Shared header. Filters work in DISPLAY (sRGB-straight) space — matching
// Photoshop, whose filters operate on document/display values. `texDisplay(uv)`
// returns display-sRGB straight color regardless of the source encoding:
//  - pass 0 reads the layer's SRGB8_ALPHA8 texture (GPU auto-decodes to LINEAR),
//    so we re-encode to sRGB (u_decodeSrc = true);
//  - later passes read an RGBA8 target that already holds sRGB-display bytes
//    (u_decodeSrc = false), passed through verbatim.
// Each filter writes display-sRGB straight bytes; the engine treats the final
// RGBA8 result as sRGB (u_srgbSource path) in the composite and on readback.
const F_HEADER = /* glsl */ `#version 300 es
precision highp float;
in vec2 v_uv;
out vec4 fragColor;
uniform sampler2D u_src;   // previous pass
uniform vec2 u_texel;      // 1/width, 1/height
uniform bool u_decodeSrc;  // true on pass 0 (source is SRGB-decoding)
vec3 _l2s(vec3 c){return mix(c*12.92, 1.055*pow(c, vec3(1.0/2.4))-0.055, step(0.0031308,c));}
vec4 texDisplay(vec2 uv){
  vec4 c = texture(u_src, uv);
  return u_decodeSrc ? vec4(_l2s(c.rgb), c.a) : c;
}
`;

function num(v: unknown, fallback = 0): number {
  return typeof v === "number" && Number.isFinite(v) ? v : fallback;
}
function bool(v: unknown, fallback = false): boolean {
  return typeof v === "boolean" ? v : fallback;
}

export const FILTERS: Record<FilterType, FilterDef> = {
  // Separable Gaussian blur. Pass 0 = horizontal, pass 1 = vertical.
  gaussian_blur: {
    type: "gaussian_blur",
    label: "Gaussian Blur",
    defaults: { radius: 4 },
    paramsSchema: [
      { kind: "slider", key: "radius", label: "Radius", min: 0, max: 100, step: 0.5, default: 4 },
    ],
    passes: () => 2,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform vec2 u_dir;     // (1,0)*texel or (0,1)*texel
uniform int  u_radius;  // <= 64
uniform float u_sigma;
void main() {
  vec4 sum = vec4(0.0);
  float wsum = 0.0;
  float s2 = 2.0 * u_sigma * u_sigma;
  for (int i = -64; i <= 64; i++) {
    if (i < -u_radius || i > u_radius) continue;
    float fi = float(i);
    float w = exp(-(fi * fi) / s2);
    sum += texDisplay(v_uv + u_dir * fi) * w;
    wsum += w;
  }
  fragColor = wsum > 0.0 ? sum / wsum : texDisplay(v_uv);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params, pass, width, height } = ctx;
      const radius = Math.min(64, Math.ceil(num(params.radius, 4)));
      const sigma = Math.max(0.5, num(params.radius, 4) / 2);
      gl.uniform1i(loc("u_radius"), radius);
      gl.uniform1f(loc("u_sigma"), sigma);
      if (pass === 0) gl.uniform2f(loc("u_dir"), 1 / width, 0);
      else gl.uniform2f(loc("u_dir"), 0, 1 / height);
    },
  },

  // Motion blur — directional box-ish sample along an angle for `distance` px.
  motion_blur: {
    type: "motion_blur",
    label: "Motion Blur",
    defaults: { angle: 0, distance: 20 },
    paramsSchema: [
      { kind: "slider", key: "angle", label: "Angle", min: -180, max: 180, step: 1, default: 0 },
      { kind: "slider", key: "distance", label: "Distance", min: 0, max: 200, step: 1, default: 20 },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform vec2 u_step;   // per-sample offset in uv
uniform int  u_samples;
void main() {
  vec4 sum = vec4(0.0);
  int n = u_samples;
  float mid = float(n - 1) * 0.5;
  for (int i = 0; i < 128; i++) {
    if (i >= n) break;
    float t = float(i) - mid;
    sum += texDisplay(v_uv + u_step * t);
  }
  fragColor = n > 0 ? sum / float(n) : texDisplay(v_uv);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params, width, height } = ctx;
      const dist = Math.max(0, num(params.distance, 20));
      const ang = (num(params.angle) * Math.PI) / 180;
      const n = Math.max(1, Math.min(127, Math.round(dist)));
      const dx = (Math.cos(ang) * dist) / Math.max(1, n - 1);
      const dy = (Math.sin(ang) * dist) / Math.max(1, n - 1);
      gl.uniform2f(loc("u_step"), dx / width, dy / height);
      gl.uniform1i(loc("u_samples"), n);
    },
  },

  // Sharpen — simple 3x3 unsharp-style kernel scaled by amount.
  sharpen: {
    type: "sharpen",
    label: "Sharpen",
    defaults: { amount: 1 },
    paramsSchema: [
      { kind: "slider", key: "amount", label: "Amount", min: 0, max: 5, step: 0.05, default: 1 },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform float u_amount;
void main() {
  vec4 c = texDisplay(v_uv);
  vec4 n = texDisplay(v_uv + vec2(0.0, -u_texel.y));
  vec4 s = texDisplay(v_uv + vec2(0.0,  u_texel.y));
  vec4 e = texDisplay(v_uv + vec2( u_texel.x, 0.0));
  vec4 w = texDisplay(v_uv + vec2(-u_texel.x, 0.0));
  vec4 lap = c * 4.0 - (n + s + e + w); // laplacian (rgb), keep alpha from c
  vec3 rgb = clamp(c.rgb + lap.rgb * u_amount, 0.0, 1.0);
  fragColor = vec4(rgb, c.a);
}
`,
    setUniforms: (ctx) => {
      ctx.gl.uniform1f(ctx.loc("u_amount"), num(ctx.params.amount, 1));
    },
  },

  // Unsharp Mask — blur (approximate, single fixed kernel) then add the
  // high-pass difference above a threshold. Single pass with a small kernel.
  unsharp_mask: {
    type: "unsharp_mask",
    label: "Unsharp Mask",
    defaults: { amount: 0.8, radius: 2, threshold: 0 },
    paramsSchema: [
      { kind: "slider", key: "amount", label: "Amount", min: 0, max: 5, step: 0.05, default: 0.8 },
      { kind: "slider", key: "radius", label: "Radius", min: 0.5, max: 10, step: 0.5, default: 2 },
      { kind: "slider", key: "threshold", label: "Threshold", min: 0, max: 1, step: 0.004, default: 0 },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform float u_amount;
uniform float u_radius;     // in px (kernel spread)
uniform float u_threshold;
void main() {
  vec4 c = texDisplay(v_uv);
  // 9-tap gaussian-ish blur with radius-scaled offsets.
  vec2 r = u_texel * u_radius;
  vec4 blur = c * 0.25;
  blur += texDisplay(v_uv + vec2( r.x, 0.0)) * 0.125;
  blur += texDisplay(v_uv + vec2(-r.x, 0.0)) * 0.125;
  blur += texDisplay(v_uv + vec2(0.0,  r.y)) * 0.125;
  blur += texDisplay(v_uv + vec2(0.0, -r.y)) * 0.125;
  blur += texDisplay(v_uv + vec2( r.x,  r.y)) * 0.0625;
  blur += texDisplay(v_uv + vec2(-r.x,  r.y)) * 0.0625;
  blur += texDisplay(v_uv + vec2( r.x, -r.y)) * 0.0625;
  blur += texDisplay(v_uv + vec2(-r.x, -r.y)) * 0.0625;
  vec3 diff = c.rgb - blur.rgb;
  float mag = max(max(abs(diff.r), abs(diff.g)), abs(diff.b));
  vec3 add = mag >= u_threshold ? diff * u_amount : vec3(0.0);
  fragColor = vec4(clamp(c.rgb + add, 0.0, 1.0), c.a);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params } = ctx;
      gl.uniform1f(loc("u_amount"), num(params.amount, 0.8));
      gl.uniform1f(loc("u_radius"), num(params.radius, 2));
      gl.uniform1f(loc("u_threshold"), num(params.threshold, 0));
    },
  },

  // Add Noise — uniform/monochrome noise, amount 0..1. The RNG seed is a fixed
  // constant (NOT Math.random per call) so the live preview is stable frame to
  // frame and the committed bake matches exactly what was previewed.
  add_noise: {
    type: "add_noise",
    label: "Add Noise",
    defaults: { amount: 0.1, monochrome: false },
    paramsSchema: [
      { kind: "slider", key: "amount", label: "Amount", min: 0, max: 1, step: 0.01, default: 0.1 },
      { kind: "checkbox", key: "monochrome", label: "Monochromatic", default: false },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform float u_amount;
uniform bool u_mono;
uniform float u_seed;
float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7)) + u_seed) * 43758.5453123);
}
void main() {
  vec4 c = texDisplay(v_uv);
  vec2 p = v_uv / u_texel;
  vec3 noise;
  if (u_mono) {
    float n = hash(p) - 0.5;
    noise = vec3(n);
  } else {
    noise = vec3(hash(p), hash(p + 17.0), hash(p + 43.0)) - 0.5;
  }
  fragColor = vec4(clamp(c.rgb + noise * u_amount, 0.0, 1.0), c.a);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params } = ctx;
      gl.uniform1f(loc("u_amount"), num(params.amount, 0.1));
      gl.uniform1i(loc("u_mono"), bool(params.monochrome) ? 1 : 0);
      // Stable seed: a fixed constant keeps the preview from flickering each
      // frame and makes the committed result identical to the preview.
      gl.uniform1f(loc("u_seed"), 137.137);
    },
  },

  // Pixelate (Mosaic) — snap uv to a cell grid and sample the cell center.
  pixelate: {
    type: "pixelate",
    label: "Pixelate",
    defaults: { cell: 10 },
    paramsSchema: [
      { kind: "slider", key: "cell", label: "Cell Size", min: 2, max: 200, step: 1, default: 10 },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform float u_cell; // px
void main() {
  vec2 px = v_uv / u_texel;          // current px
  vec2 cell = max(u_cell, 1.0) * (floor(px / max(u_cell, 1.0)) + 0.5);
  fragColor = texDisplay(cell * u_texel);
}
`,
    setUniforms: (ctx) => {
      ctx.gl.uniform1f(ctx.loc("u_cell"), Math.max(1, num(ctx.params.cell, 10)));
    },
  },

  // Find Edges — Sobel magnitude, inverted (white bg, dark edges) like PS.
  find_edges: {
    type: "find_edges",
    label: "Find Edges",
    defaults: {},
    paramsSchema: [],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
float lum(vec3 c) { return dot(c, vec3(0.299, 0.587, 0.114)); }
void main() {
  vec2 t = u_texel;
  float tl = lum(texDisplay(v_uv + vec2(-t.x, -t.y)).rgb);
  float tm = lum(texDisplay(v_uv + vec2( 0.0, -t.y)).rgb);
  float tr = lum(texDisplay(v_uv + vec2( t.x, -t.y)).rgb);
  float ml = lum(texDisplay(v_uv + vec2(-t.x, 0.0)).rgb);
  float mr = lum(texDisplay(v_uv + vec2( t.x, 0.0)).rgb);
  float bl = lum(texDisplay(v_uv + vec2(-t.x, t.y)).rgb);
  float bm = lum(texDisplay(v_uv + vec2( 0.0, t.y)).rgb);
  float br = lum(texDisplay(v_uv + vec2( t.x, t.y)).rgb);
  float gx = -tl - 2.0*ml - bl + tr + 2.0*mr + br;
  float gy = -tl - 2.0*tm - tr + bl + 2.0*bm + br;
  float mag = clamp(length(vec2(gx, gy)), 0.0, 1.0);
  float e = 1.0 - mag; // invert: edges dark on white
  float a = texDisplay(v_uv).a;
  fragColor = vec4(vec3(e), a);
}
`,
    setUniforms: () => {},
  },

  // Emboss — directional gradient + 0.5 bias (grey relief).
  emboss: {
    type: "emboss",
    label: "Emboss",
    defaults: { angle: 135, amount: 1 },
    paramsSchema: [
      { kind: "slider", key: "angle", label: "Angle", min: -180, max: 180, step: 1, default: 135 },
      { kind: "slider", key: "amount", label: "Amount", min: 0, max: 5, step: 0.05, default: 1 },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform vec2 u_dir;    // direction * texel
uniform float u_amount;
float lum(vec3 c) { return dot(c, vec3(0.299, 0.587, 0.114)); }
void main() {
  float a0 = lum(texDisplay(v_uv - u_dir).rgb);
  float a1 = lum(texDisplay(v_uv + u_dir).rgb);
  float e = 0.5 + (a1 - a0) * u_amount;
  float a = texDisplay(v_uv).a;
  fragColor = vec4(vec3(clamp(e, 0.0, 1.0)), a);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params, width, height } = ctx;
      const ang = (num(params.angle, 135) * Math.PI) / 180;
      gl.uniform2f(loc("u_dir"), Math.cos(ang) / width, Math.sin(ang) / height);
      gl.uniform1f(loc("u_amount"), num(params.amount, 1));
    },
  },
};

/** Ordered list for the Filter menu. */
export const FILTER_ORDER: FilterType[] = [
  "gaussian_blur",
  "motion_blur",
  "sharpen",
  "unsharp_mask",
  "add_noise",
  "pixelate",
  "find_edges",
  "emboss",
];

/** Deep-clone a filter's defaults. */
export function defaultFilterParams(type: FilterType): FilterParams {
  return structuredClone(FILTERS[type].defaults);
}
