/**
 * Destructive filter registry.
 *
 * Unlike adjustment layers (which are non-destructive fullscreen passes over
 * the live composite), filters render a SINGLE raster layer's pixels through
 * one or more shader passes into an RGBA8 target, read the result back, and
 * replace the layer's CPU source as one undo step. Some filters need two passes
 * (separable blur) — the engine drives the pass loop, ping-ponging between two
 * RGBA8 targets, and a filter declares how many passes it wants and supplies
 * per-pass uniforms.
 *
 * All filter shaders operate on STRAIGHT-alpha sRGB layer textures (the same
 * encoding a layer's source uses), so they are display-referred. Each shader
 * samples `u_src` (the previous pass / the layer) and writes the next pass.
 *
 * The registry is data-driven (`paramsSchema`) so dialogs are generated by the
 * UI without hard-coding per-filter forms.
 */
import type { ParamField, AdjustmentParams as ParamBag } from "./adjustments";

export type FilterType =
  | "gaussian_blur"
  | "motion_blur"
  | "sharpen"
  | "unsharp_mask"
  | "add_noise"
  | "pixelate"
  | "find_edges"
  | "emboss"
  | "vignette"
  | "chromatic_aberration"
  | "halftone"
  | "lens_blur"
  | "oil_paint"
  | "clarity";

export type FilterParams = ParamBag;

/** Per-pass uniform setter context. */
export interface FilterPassContext {
  gl: WebGL2RenderingContext;
  loc: (name: string) => WebGLUniformLocation | null;
  params: FilterParams;
  /** 0-based pass index (for multi-pass filters like separable blur). */
  pass: number;
  /** Layer pixel dimensions (for texel-size uniforms). */
  width: number;
  height: number;
}

export interface FilterDef {
  type: FilterType;
  label: string;
  defaults: FilterParams;
  paramsSchema: ParamField[];
  /** Fragment shader source (uses QUAD_VERT; samples u_src). */
  fragSource: string;
  /**
   * Number of render passes. May depend on params (e.g. a 0-radius blur could
   * short-circuit, but we keep it simple and always run the declared count).
   */
  passes: (params: FilterParams) => number;
  /** Push per-pass uniforms (the engine binds u_src + sets u_texel for you). */
  setUniforms: (ctx: FilterPassContext) => void;
}

// Shared header. Filters work in DISPLAY (sRGB-straight) space — matching
// Photoshop, whose filters operate on document/display values. `texDisplay(uv)`
// returns display-sRGB straight color regardless of the source encoding:
//  - pass 0 reads the layer's SRGB8_ALPHA8 texture (GPU auto-decodes to LINEAR),
//    so we re-encode to sRGB (u_decodeSrc = true);
//  - later passes read an RGBA8 target that already holds sRGB-display bytes
//    (u_decodeSrc = false), passed through verbatim.
// Each filter writes display-sRGB straight bytes; the engine treats the final
// RGBA8 result as sRGB (u_srgbSource path) in the composite and on readback.
const F_HEADER = /* glsl */ `#version 300 es
precision highp float;
in vec2 v_uv;
out vec4 fragColor;
uniform sampler2D u_src;   // previous pass
uniform vec2 u_texel;      // 1/width, 1/height
uniform bool u_decodeSrc;  // true on pass 0 (source is SRGB-decoding)
vec3 _l2s(vec3 c){return mix(c*12.92, 1.055*pow(c, vec3(1.0/2.4))-0.055, step(0.0031308,c));}
vec4 texDisplay(vec2 uv){
  vec4 c = texture(u_src, uv);
  return u_decodeSrc ? vec4(_l2s(c.rgb), c.a) : c;
}
`;

function num(v: unknown, fallback = 0): number {
  return typeof v === "number" && Number.isFinite(v) ? v : fallback;
}
function bool(v: unknown, fallback = false): boolean {
  return typeof v === "boolean" ? v : fallback;
}

export const FILTERS: Record<FilterType, FilterDef> = {
  // Separable Gaussian blur. Pass 0 = horizontal, pass 1 = vertical.
  gaussian_blur: {
    type: "gaussian_blur",
    label: "Gaussian Blur",
    defaults: { radius: 4 },
    paramsSchema: [
      { kind: "slider", key: "radius", label: "Radius", min: 0, max: 100, step: 0.5, default: 4 },
    ],
    passes: () => 2,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform vec2 u_dir;     // (1,0)*texel or (0,1)*texel
uniform int  u_radius;  // <= 64
uniform float u_sigma;
void main() {
  vec4 sum = vec4(0.0);
  float wsum = 0.0;
  float s2 = 2.0 * u_sigma * u_sigma;
  for (int i = -64; i <= 64; i++) {
    if (i < -u_radius || i > u_radius) continue;
    float fi = float(i);
    float w = exp(-(fi * fi) / s2);
    sum += texDisplay(v_uv + u_dir * fi) * w;
    wsum += w;
  }
  fragColor = wsum > 0.0 ? sum / wsum : texDisplay(v_uv);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params, pass, width, height } = ctx;
      const radius = Math.min(64, Math.ceil(num(params.radius, 4)));
      const sigma = Math.max(0.5, num(params.radius, 4) / 2);
      gl.uniform1i(loc("u_radius"), radius);
      gl.uniform1f(loc("u_sigma"), sigma);
      if (pass === 0) gl.uniform2f(loc("u_dir"), 1 / width, 0);
      else gl.uniform2f(loc("u_dir"), 0, 1 / height);
    },
  },

  // Motion blur — directional box-ish sample along an angle for `distance` px.
  motion_blur: {
    type: "motion_blur",
    label: "Motion Blur",
    defaults: { angle: 0, distance: 20 },
    paramsSchema: [
      { kind: "slider", key: "angle", label: "Angle", min: -180, max: 180, step: 1, default: 0 },
      { kind: "slider", key: "distance", label: "Distance", min: 0, max: 200, step: 1, default: 20 },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform vec2 u_step;   // per-sample offset in uv
uniform int  u_samples;
void main() {
  vec4 sum = vec4(0.0);
  int n = u_samples;
  float mid = float(n - 1) * 0.5;
  for (int i = 0; i < 128; i++) {
    if (i >= n) break;
    float t = float(i) - mid;
    sum += texDisplay(v_uv + u_step * t);
  }
  fragColor = n > 0 ? sum / float(n) : texDisplay(v_uv);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params, width, height } = ctx;
      const dist = Math.max(0, num(params.distance, 20));
      const ang = (num(params.angle) * Math.PI) / 180;
      const n = Math.max(1, Math.min(127, Math.round(dist)));
      const dx = (Math.cos(ang) * dist) / Math.max(1, n - 1);
      const dy = (Math.sin(ang) * dist) / Math.max(1, n - 1);
      gl.uniform2f(loc("u_step"), dx / width, dy / height);
      gl.uniform1i(loc("u_samples"), n);
    },
  },

  // Sharpen — simple 3x3 unsharp-style kernel scaled by amount.
  sharpen: {
    type: "sharpen",
    label: "Sharpen",
    defaults: { amount: 1 },
    paramsSchema: [
      { kind: "slider", key: "amount", label: "Amount", min: 0, max: 5, step: 0.05, default: 1 },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform float u_amount;
void main() {
  vec4 c = texDisplay(v_uv);
  vec4 n = texDisplay(v_uv + vec2(0.0, -u_texel.y));
  vec4 s = texDisplay(v_uv + vec2(0.0,  u_texel.y));
  vec4 e = texDisplay(v_uv + vec2( u_texel.x, 0.0));
  vec4 w = texDisplay(v_uv + vec2(-u_texel.x, 0.0));
  vec4 lap = c * 4.0 - (n + s + e + w); // laplacian (rgb), keep alpha from c
  vec3 rgb = clamp(c.rgb + lap.rgb * u_amount, 0.0, 1.0);
  fragColor = vec4(rgb, c.a);
}
`,
    setUniforms: (ctx) => {
      ctx.gl.uniform1f(ctx.loc("u_amount"), num(ctx.params.amount, 1));
    },
  },

  // Unsharp Mask — blur (approximate, single fixed kernel) then add the
  // high-pass difference above a threshold. Single pass with a small kernel.
  unsharp_mask: {
    type: "unsharp_mask",
    label: "Unsharp Mask",
    defaults: { amount: 0.8, radius: 2, threshold: 0 },
    paramsSchema: [
      { kind: "slider", key: "amount", label: "Amount", min: 0, max: 5, step: 0.05, default: 0.8 },
      { kind: "slider", key: "radius", label: "Radius", min: 0.5, max: 10, step: 0.5, default: 2 },
      { kind: "slider", key: "threshold", label: "Threshold", min: 0, max: 1, step: 0.004, default: 0 },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform float u_amount;
uniform float u_radius;     // in px (kernel spread)
uniform float u_threshold;
void main() {
  vec4 c = texDisplay(v_uv);
  // 9-tap gaussian-ish blur with radius-scaled offsets.
  vec2 r = u_texel * u_radius;
  vec4 blur = c * 0.25;
  blur += texDisplay(v_uv + vec2( r.x, 0.0)) * 0.125;
  blur += texDisplay(v_uv + vec2(-r.x, 0.0)) * 0.125;
  blur += texDisplay(v_uv + vec2(0.0,  r.y)) * 0.125;
  blur += texDisplay(v_uv + vec2(0.0, -r.y)) * 0.125;
  blur += texDisplay(v_uv + vec2( r.x,  r.y)) * 0.0625;
  blur += texDisplay(v_uv + vec2(-r.x,  r.y)) * 0.0625;
  blur += texDisplay(v_uv + vec2( r.x, -r.y)) * 0.0625;
  blur += texDisplay(v_uv + vec2(-r.x, -r.y)) * 0.0625;
  vec3 diff = c.rgb - blur.rgb;
  float mag = max(max(abs(diff.r), abs(diff.g)), abs(diff.b));
  vec3 add = mag >= u_threshold ? diff * u_amount : vec3(0.0);
  fragColor = vec4(clamp(c.rgb + add, 0.0, 1.0), c.a);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params } = ctx;
      gl.uniform1f(loc("u_amount"), num(params.amount, 0.8));
      gl.uniform1f(loc("u_radius"), num(params.radius, 2));
      gl.uniform1f(loc("u_threshold"), num(params.threshold, 0));
    },
  },

  // Add Noise — uniform/monochrome noise, amount 0..1. The RNG seed is a fixed
  // constant (NOT Math.random per call) so the live preview is stable frame to
  // frame and the committed bake matches exactly what was previewed.
  add_noise: {
    type: "add_noise",
    label: "Add Noise",
    defaults: { amount: 0.1, monochrome: false },
    paramsSchema: [
      { kind: "slider", key: "amount", label: "Amount", min: 0, max: 1, step: 0.01, default: 0.1 },
      { kind: "checkbox", key: "monochrome", label: "Monochromatic", default: false },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform float u_amount;
uniform bool u_mono;
uniform float u_seed;
float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7)) + u_seed) * 43758.5453123);
}
void main() {
  vec4 c = texDisplay(v_uv);
  vec2 p = v_uv / u_texel;
  vec3 noise;
  if (u_mono) {
    float n = hash(p) - 0.5;
    noise = vec3(n);
  } else {
    noise = vec3(hash(p), hash(p + 17.0), hash(p + 43.0)) - 0.5;
  }
  fragColor = vec4(clamp(c.rgb + noise * u_amount, 0.0, 1.0), c.a);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params } = ctx;
      gl.uniform1f(loc("u_amount"), num(params.amount, 0.1));
      gl.uniform1i(loc("u_mono"), bool(params.monochrome) ? 1 : 0);
      // Stable seed: a fixed constant keeps the preview from flickering each
      // frame and makes the committed result identical to the preview.
      gl.uniform1f(loc("u_seed"), 137.137);
    },
  },

  // Pixelate (Mosaic) — snap uv to a cell grid and sample the cell center.
  pixelate: {
    type: "pixelate",
    label: "Pixelate",
    defaults: { cell: 10 },
    paramsSchema: [
      { kind: "slider", key: "cell", label: "Cell Size", min: 2, max: 200, step: 1, default: 10 },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform float u_cell; // px
void main() {
  vec2 px = v_uv / u_texel;          // current px
  vec2 cell = max(u_cell, 1.0) * (floor(px / max(u_cell, 1.0)) + 0.5);
  fragColor = texDisplay(cell * u_texel);
}
`,
    setUniforms: (ctx) => {
      ctx.gl.uniform1f(ctx.loc("u_cell"), Math.max(1, num(ctx.params.cell, 10)));
    },
  },

  // Find Edges — Sobel magnitude, inverted (white bg, dark edges) like PS.
  find_edges: {
    type: "find_edges",
    label: "Find Edges",
    defaults: {},
    paramsSchema: [],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
float lum(vec3 c) { return dot(c, vec3(0.299, 0.587, 0.114)); }
void main() {
  vec2 t = u_texel;
  float tl = lum(texDisplay(v_uv + vec2(-t.x, -t.y)).rgb);
  float tm = lum(texDisplay(v_uv + vec2( 0.0, -t.y)).rgb);
  float tr = lum(texDisplay(v_uv + vec2( t.x, -t.y)).rgb);
  float ml = lum(texDisplay(v_uv + vec2(-t.x, 0.0)).rgb);
  float mr = lum(texDisplay(v_uv + vec2( t.x, 0.0)).rgb);
  float bl = lum(texDisplay(v_uv + vec2(-t.x, t.y)).rgb);
  float bm = lum(texDisplay(v_uv + vec2( 0.0, t.y)).rgb);
  float br = lum(texDisplay(v_uv + vec2( t.x, t.y)).rgb);
  float gx = -tl - 2.0*ml - bl + tr + 2.0*mr + br;
  float gy = -tl - 2.0*tm - tr + bl + 2.0*bm + br;
  float mag = clamp(length(vec2(gx, gy)), 0.0, 1.0);
  float e = 1.0 - mag; // invert: edges dark on white
  float a = texDisplay(v_uv).a;
  fragColor = vec4(vec3(e), a);
}
`,
    setUniforms: () => {},
  },

  // Emboss — directional gradient + 0.5 bias (grey relief).
  emboss: {
    type: "emboss",
    label: "Emboss",
    defaults: { angle: 135, amount: 1 },
    paramsSchema: [
      { kind: "slider", key: "angle", label: "Angle", min: -180, max: 180, step: 1, default: 135 },
      { kind: "slider", key: "amount", label: "Amount", min: 0, max: 5, step: 0.05, default: 1 },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform vec2 u_dir;    // direction * texel
uniform float u_amount;
float lum(vec3 c) { return dot(c, vec3(0.299, 0.587, 0.114)); }
void main() {
  float a0 = lum(texDisplay(v_uv - u_dir).rgb);
  float a1 = lum(texDisplay(v_uv + u_dir).rgb);
  float e = 0.5 + (a1 - a0) * u_amount;
  float a = texDisplay(v_uv).a;
  fragColor = vec4(vec3(clamp(e, 0.0, 1.0)), a);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params, width, height } = ctx;
      const ang = (num(params.angle, 135) * Math.PI) / 180;
      gl.uniform2f(loc("u_dir"), Math.cos(ang) / width, Math.sin(ang) / height);
      gl.uniform1f(loc("u_amount"), num(params.amount, 1));
    },
  },

  // Vignette — radial darkening toward the edges. `midpoint` sets where the
  // falloff begins (0 = center, 1 = corners), `feather` softens the transition,
  // `roundness` morphs between an ellipse fitted to the layer (0) and a circle
  // (1). The darkening is applied in DISPLAY space (matches PS lens-vignette).
  vignette: {
    type: "vignette",
    label: "Vignette",
    defaults: { amount: 0.5, midpoint: 0.5, roundness: 0.5, feather: 0.5 },
    paramsSchema: [
      { kind: "slider", key: "amount", label: "Amount", min: 0, max: 1, step: 0.01, default: 0.5 },
      { kind: "slider", key: "midpoint", label: "Midpoint", min: 0, max: 1, step: 0.01, default: 0.5 },
      { kind: "slider", key: "roundness", label: "Roundness", min: 0, max: 1, step: 0.01, default: 0.5 },
      { kind: "slider", key: "feather", label: "Feather", min: 0.01, max: 1, step: 0.01, default: 0.5 },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform float u_amount;
uniform float u_midpoint;
uniform float u_roundness;
uniform float u_feather;
uniform float u_aspect;   // width / height
void main() {
  vec4 c = texDisplay(v_uv);
  // Centered coords; scale x toward circular as roundness -> 1.
  vec2 d = (v_uv - 0.5) * 2.0;
  d.x *= mix(u_aspect, 1.0, u_roundness);
  float r = length(d);
  // Falloff: fully lit inside the midpoint radius, ramping to full darkening
  // over the feather band toward the corner radius.
  float inner = u_midpoint;
  float outer = u_midpoint + u_feather;
  float v = smoothstep(inner, outer, r);
  float darken = 1.0 - v * u_amount;
  fragColor = vec4(clamp(c.rgb * darken, 0.0, 1.0), c.a);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params, width, height } = ctx;
      gl.uniform1f(loc("u_amount"), num(params.amount, 0.5));
      gl.uniform1f(loc("u_midpoint"), num(params.midpoint, 0.5));
      gl.uniform1f(loc("u_roundness"), num(params.roundness, 0.5));
      gl.uniform1f(loc("u_feather"), Math.max(0.01, num(params.feather, 0.5)));
      gl.uniform1f(loc("u_aspect"), Math.max(1e-3, width / Math.max(1, height)));
    },
  },

  // Chromatic Aberration — offset the R and B channels radially outward from the
  // center (lateral CA). `amount` is the max channel shift in px at the corner.
  // `edgeOnly` ramps the shift with radius^2 so the center stays crisp.
  chromatic_aberration: {
    type: "chromatic_aberration",
    label: "Chromatic Aberration",
    defaults: { amount: 6, edgeOnly: true },
    paramsSchema: [
      { kind: "slider", key: "amount", label: "Amount", min: 0, max: 40, step: 0.5, default: 6 },
      { kind: "checkbox", key: "edgeOnly", label: "Stronger at Edges", default: true },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform float u_amount;   // px at the corner
uniform bool u_edgeOnly;
void main() {
  vec2 dir = v_uv - 0.5;
  float r = length(dir) / 0.7071;          // 0 at center, ~1 at corner
  float falloff = u_edgeOnly ? r * r : r;
  // Shift in uv: amount px * texel, along the radial direction.
  vec2 off = normalize(dir + vec2(1e-6)) * (u_amount * falloff) * u_texel;
  float a = texDisplay(v_uv).a;
  float rch = texDisplay(v_uv + off).r;     // R pushed out
  float gch = texDisplay(v_uv).g;           // G stays
  float bch = texDisplay(v_uv - off).b;     // B pulled in
  fragColor = vec4(rch, gch, bch, a);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params } = ctx;
      gl.uniform1f(loc("u_amount"), Math.max(0, num(params.amount, 6)));
      gl.uniform1i(loc("u_edgeOnly"), bool(params.edgeOnly, true) ? 1 : 0);
    },
  },

  // Halftone — newsprint dot screen. The image is sampled on a rotated grid and
  // each cell becomes a dot whose radius tracks the cell's luminance (mono) or
  // per-channel value (CMY-ish color screen at staggered angles).
  halftone: {
    type: "halftone",
    label: "Halftone",
    defaults: { cellSize: 8, angle: 45, monochrome: true },
    paramsSchema: [
      { kind: "slider", key: "cellSize", label: "Cell Size", min: 2, max: 40, step: 1, default: 8 },
      { kind: "slider", key: "angle", label: "Angle", min: 0, max: 90, step: 1, default: 45 },
      { kind: "checkbox", key: "monochrome", label: "Monochrome", default: true },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform float u_cell;     // px
uniform float u_angle;    // radians
uniform bool u_mono;
float lum(vec3 c){ return dot(c, vec3(0.299, 0.587, 0.114)); }
// Dot coverage for value v (0=dark) at rotated screen angle ang. Returns the
// ink amount 0..1 at the current pixel for that screen.
float screen(vec2 px, float v, float ang) {
  float s = sin(ang), co = cos(ang);
  mat2 rot = mat2(co, -s, s, co);
  vec2 rp = rot * px;
  vec2 cell = mod(rp, u_cell) - u_cell * 0.5;
  float dist = length(cell);
  // Darker value -> bigger dot. Radius up to half the cell diagonal.
  float radius = (1.0 - v) * u_cell * 0.5 * 1.42;
  return 1.0 - smoothstep(radius - 1.0, radius + 1.0, dist);
}
void main() {
  vec4 c = texDisplay(v_uv);
  vec2 px = v_uv / u_texel;
  if (u_mono) {
    float v = lum(c.rgb);
    float ink = screen(px, v, u_angle);
    fragColor = vec4(vec3(1.0 - ink), c.a);   // ink black on white
  } else {
    // CMY screens at classic stagger; K not separated (keeps it simple).
    float cy = screen(px, c.r, u_angle + 0.2618);          // ~15deg
    float mg = screen(px, c.g, u_angle + 1.309);           // ~75deg
    float yl = screen(px, c.b, u_angle);                   // 0deg
    vec3 rgb = vec3(1.0) - vec3(cy, mg, yl);
    fragColor = vec4(rgb, c.a);
  }
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params } = ctx;
      gl.uniform1f(loc("u_cell"), Math.max(2, num(params.cellSize, 8)));
      gl.uniform1f(loc("u_angle"), (num(params.angle, 45) * Math.PI) / 180);
      gl.uniform1i(loc("u_mono"), bool(params.monochrome, true) ? 1 : 0);
    },
  },

  // Lens Blur — disc/bokeh blur. Samples a fixed-count spiral disc kernel (the
  // sample count scales with radius up to a cap). Highlights are gently boosted
  // before averaging so bright points bloom into bokeh discs (approximate).
  lens_blur: {
    type: "lens_blur",
    label: "Lens Blur",
    defaults: { radius: 8, brightnessBoost: 0.3 },
    paramsSchema: [
      { kind: "slider", key: "radius", label: "Radius", min: 0, max: 60, step: 0.5, default: 8 },
      { kind: "slider", key: "brightnessBoost", label: "Highlight Bloom", min: 0, max: 1, step: 0.01, default: 0.3 },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform float u_radius;   // px
uniform int   u_samples;
uniform float u_boost;
// Golden-angle spiral disc sampling — even disc coverage with a fixed budget.
const float GA = 2.39996323;
void main() {
  if (u_radius < 0.5) { fragColor = texDisplay(v_uv); return; }
  vec4 sum = vec4(0.0);
  float wsum = 0.0;
  int n = u_samples;
  for (int i = 0; i < 256; i++) {
    if (i >= n) break;
    float fi = float(i);
    float t = (fi + 0.5) / float(n);
    float rr = sqrt(t) * u_radius;        // uniform disc radius
    float ang = fi * GA;
    vec2 off = vec2(cos(ang), sin(ang)) * rr * u_texel;
    vec4 s = texDisplay(v_uv + off);
    // Highlight weighting: brighter samples count a touch more, so bright
    // points spread into rounded bokeh instead of just averaging out.
    float l = dot(s.rgb, vec3(0.299, 0.587, 0.114));
    float w = 1.0 + u_boost * pow(l, 3.0) * 3.0;
    sum += s * w;
    wsum += w;
  }
  fragColor = wsum > 0.0 ? sum / wsum : texDisplay(v_uv);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params } = ctx;
      const radius = Math.max(0, num(params.radius, 8));
      // Sample budget grows with area, capped at 256 (shader loop bound).
      const n = Math.max(8, Math.min(256, Math.round(radius * radius * 0.9) + 12));
      gl.uniform1f(loc("u_radius"), radius);
      gl.uniform1i(loc("u_samples"), n);
      gl.uniform1f(loc("u_boost"), num(params.brightnessBoost, 0.3));
    },
  },

  // Oil Paint — Kuwahara-style painterly stylize. The neighborhood is split into
  // four overlapping quadrant windows; the quadrant with the lowest luminance
  // variance wins and its mean color is output, flattening detail into smooth
  // "brushed" regions while preserving edges. `intensity` blends toward the
  // original so the effect can be eased in.
  oil_paint: {
    type: "oil_paint",
    label: "Oil Paint",
    defaults: { radius: 4, intensity: 1 },
    paramsSchema: [
      { kind: "slider", key: "radius", label: "Radius", min: 1, max: 10, step: 1, default: 4 },
      { kind: "slider", key: "intensity", label: "Intensity", min: 0, max: 1, step: 0.01, default: 1 },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform int u_radius;     // window half-size in px (<= 10)
uniform float u_intensity;
float lum(vec3 c){ return dot(c, vec3(0.299, 0.587, 0.114)); }
void main() {
  vec4 src = texDisplay(v_uv);
  int rad = u_radius;
  // Accumulate the four Kuwahara quadrants: mean color + luminance variance.
  vec3 qmean[4];
  float qvar[4];
  for (int q = 0; q < 4; q++) { qmean[q] = vec3(0.0); qvar[q] = 0.0; }
  // Quadrant offset signs: (-,-), (+,-), (-,+), (+,+).
  for (int q = 0; q < 4; q++) {
    vec2 sgn = vec2(q == 1 || q == 3 ? 1.0 : -1.0, q >= 2 ? 1.0 : -1.0);
    vec3 sumC = vec3(0.0);
    float sumL = 0.0, sumL2 = 0.0, cnt = 0.0;
    for (int dy = 0; dy <= 10; dy++) {
      if (dy > rad) break;
      for (int dx = 0; dx <= 10; dx++) {
        if (dx > rad) break;
        vec2 off = vec2(float(dx) * sgn.x, float(dy) * sgn.y) * u_texel;
        vec3 c = texDisplay(v_uv + off).rgb;
        float l = lum(c);
        sumC += c; sumL += l; sumL2 += l * l; cnt += 1.0;
      }
    }
    qmean[q] = sumC / cnt;
    float m = sumL / cnt;
    qvar[q] = sumL2 / cnt - m * m;
  }
  // Pick the lowest-variance (flattest) quadrant.
  vec3 best = qmean[0];
  float bestVar = qvar[0];
  for (int q = 1; q < 4; q++) {
    if (qvar[q] < bestVar) { bestVar = qvar[q]; best = qmean[q]; }
  }
  vec3 outc = mix(src.rgb, best, clamp(u_intensity, 0.0, 1.0));
  fragColor = vec4(outc, src.a);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params } = ctx;
      gl.uniform1i(loc("u_radius"), Math.max(1, Math.min(10, Math.round(num(params.radius, 4)))));
      gl.uniform1f(loc("u_intensity"), num(params.intensity, 1));
    },
  },

  // Clarity — local-contrast (midtone) boost. We estimate a large-radius blurred
  // "base" in ONE pass with a wide ring of weighted taps, then add the high-pass
  // (image - base) back, weighted by a midtone bell so shadows/highlights aren't
  // crushed. Single pass keeps it self-contained (the original layer is u_src on
  // pass 0, so image and base come from the same sampler). `amount` can go
  // negative to SOFTEN local contrast.
  clarity: {
    type: "clarity",
    label: "Clarity",
    defaults: { amount: 0.4 },
    paramsSchema: [
      { kind: "slider", key: "amount", label: "Amount", min: -1, max: 1, step: 0.01, default: 0.4 },
    ],
    passes: () => 1,
    fragSource:
      F_HEADER +
      /* glsl */ `
uniform float u_amount;
uniform float u_radius;   // base-blur spread in px
float lum(vec3 c){ return dot(c, vec3(0.299, 0.587, 0.114)); }
void main() {
  vec4 c = texDisplay(v_uv);
  // Wide separable-ish ring blur (25 taps on a 5x5 weighted lattice scaled by
  // radius) approximating the low-frequency base for a large-radius high-pass.
  vec2 r = u_texel * u_radius;
  vec3 base = vec3(0.0);
  float wsum = 0.0;
  for (int j = -2; j <= 2; j++) {
    for (int i = -2; i <= 2; i++) {
      vec2 off = vec2(float(i), float(j)) * r;
      // Gaussian-ish weight by lattice distance.
      float w = exp(-(float(i*i + j*j)) / 4.0);
      base += texDisplay(v_uv + off).rgb * w;
      wsum += w;
    }
  }
  base /= max(wsum, 1e-4);
  vec3 high = c.rgb - base;
  // Midtone bell weight (peaks at 0.5 luminance, eases shadows/highlights).
  float l = lum(c.rgb);
  float midtone = 1.0 - pow(clamp(abs(l - 0.5) * 2.0, 0.0, 1.0), 2.0);
  vec3 outc = clamp(c.rgb + high * u_amount * 1.5 * midtone, 0.0, 1.0);
  fragColor = vec4(outc, c.a);
}
`,
    setUniforms: (ctx) => {
      const { gl, loc, params, width, height } = ctx;
      // Wide base blur (clarity is a large-radius unsharp); spread scales with
      // the layer so it reads as LOCAL contrast, not edge sharpening.
      const radius = Math.max(4, Math.min(40, Math.round(Math.min(width, height) * 0.02)));
      gl.uniform1f(loc("u_radius"), radius);
      gl.uniform1f(loc("u_amount"), num(params.amount, 0.4));
    },
  },
};

/** Ordered list for the Filter menu. */
export const FILTER_ORDER: FilterType[] = [
  "gaussian_blur",
  "lens_blur",
  "motion_blur",
  "sharpen",
  "unsharp_mask",
  "clarity",
  "add_noise",
  "pixelate",
  "find_edges",
  "emboss",
  "oil_paint",
  "halftone",
  "vignette",
  "chromatic_aberration",
];

/** Deep-clone a filter's defaults. */
export function defaultFilterParams(type: FilterType): FilterParams {
  return structuredClone(FILTERS[type].defaults);
}
